title: <p align="center"> Nilesh Maurya </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nilesh-maurya-63503b1bb">LinkedIn</a> |
  <a href="https://github.com/Nil1403">GitHub</a>
  
  <br>   
I am working as Full Stack Developer in Software AG,I'm online instructors also have my own youtube channel "CODE WITH NM" where I teach programming languages concept and much more.  
  <br>
  </p>



theme: jekyll-theme-time-machine
